# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e29d498b816ae90ce1476f33108402be94d5ca7f56e2d099d6af3bc198208cd9211be6287f68e833f4f4e1edcf68c75f0df755b06552c9d134d1c843c3d859

test:
  secret_key_base: f01ffa671a0616e80a1f9f45f98b7beefa06b3e92cf6c8ca8905c4ede2907e318b36e57918f03ed3509b4346d9e225fc707f2a429868e956db8c1b77ec375ec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_BRANTA_KEY"] %>
