#!/bin/sh
# Run the server.

set -e

if [ "$RAILS_ENV" != "production" ]; then
  pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
fi

echo "==> Running on http://0.0.0.0:5000/ …"

RAILS_ENV=development rerun foreman start
